name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.x", "1.24.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Version
        run: go version
      - name: Install
        run: go mod download
      - name: Vet
        run: go vet ./...
      - name: Build
        run: go build -v -trimpath ./...
      - name: Test
        run: go test -race -count 1 ./...
      - name: Bench
        run: go test -benchmem -bench BenchmarkConfig github.com/boolka/goconfig/pkg/config/config_test
