name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.24.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Version
        run: go version
      - name: Install
        run: go mod download
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test ./...
      - name: Bench
        run: go test -benchmem -bench BenchmarkConfig github.com/boolka/goconfig/pkg/config/config_test
