name: Vault

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.23.x", "1.24.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker
        uses: docker/setup-docker-action@v4
      - name: Test Docker
        run: |
          docker version
          docker info
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Version
        run: go version
      - name: Install
        run: go mod download
      - name: Vault
        run: |
          docker run -d -p 8200:8200 hashicorp/vault server -dev -dev-root-token-id=root start
          sleep 10
          docker ps -a
      - name: Test
        run: go test -race -tags vault -count 1 ./...
